	soc_system u0 (
		.button_pio_export                      (<connected-to-button_pio_export>),                      //                       button_pio.export
		.cgm_clk                                (<connected-to-cgm_clk>),                                //                              cgm.clk
		.dipsw_pio_export                       (<connected-to-dipsw_pio_export>),                       //                        dipsw_pio.export
		.f2sdram_only_master_master_reset_reset (<connected-to-f2sdram_only_master_master_reset_reset>), // f2sdram_only_master_master_reset.reset
		.hex_pio_export                         (<connected-to-hex_pio_export>),                         //                          hex_pio.export
		.hps_0_f2h_cold_rst_req_n               (<connected-to-hps_0_f2h_cold_rst_req_n>),               //         hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_dbg_rst_req_n                (<connected-to-hps_0_f2h_dbg_rst_req_n>),                //        hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hwevents                 (<connected-to-hps_0_f2h_stm_hwevents>),                 //          hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_rst_req_n               (<connected-to-hps_0_f2h_warm_rst_req_n>),               //         hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_AWID                         (<connected-to-hps_0_h2f_AWID>),                         //             hps_0_h2f_axi_master.awid
		.hps_0_h2f_AWADDR                       (<connected-to-hps_0_h2f_AWADDR>),                       //                                 .awaddr
		.hps_0_h2f_AWLEN                        (<connected-to-hps_0_h2f_AWLEN>),                        //                                 .awlen
		.hps_0_h2f_AWSIZE                       (<connected-to-hps_0_h2f_AWSIZE>),                       //                                 .awsize
		.hps_0_h2f_AWBURST                      (<connected-to-hps_0_h2f_AWBURST>),                      //                                 .awburst
		.hps_0_h2f_AWLOCK                       (<connected-to-hps_0_h2f_AWLOCK>),                       //                                 .awlock
		.hps_0_h2f_AWCACHE                      (<connected-to-hps_0_h2f_AWCACHE>),                      //                                 .awcache
		.hps_0_h2f_AWPROT                       (<connected-to-hps_0_h2f_AWPROT>),                       //                                 .awprot
		.hps_0_h2f_AWVALID                      (<connected-to-hps_0_h2f_AWVALID>),                      //                                 .awvalid
		.hps_0_h2f_AWREADY                      (<connected-to-hps_0_h2f_AWREADY>),                      //                                 .awready
		.hps_0_h2f_WID                          (<connected-to-hps_0_h2f_WID>),                          //                                 .wid
		.hps_0_h2f_WDATA                        (<connected-to-hps_0_h2f_WDATA>),                        //                                 .wdata
		.hps_0_h2f_WSTRB                        (<connected-to-hps_0_h2f_WSTRB>),                        //                                 .wstrb
		.hps_0_h2f_WLAST                        (<connected-to-hps_0_h2f_WLAST>),                        //                                 .wlast
		.hps_0_h2f_WVALID                       (<connected-to-hps_0_h2f_WVALID>),                       //                                 .wvalid
		.hps_0_h2f_WREADY                       (<connected-to-hps_0_h2f_WREADY>),                       //                                 .wready
		.hps_0_h2f_BID                          (<connected-to-hps_0_h2f_BID>),                          //                                 .bid
		.hps_0_h2f_BRESP                        (<connected-to-hps_0_h2f_BRESP>),                        //                                 .bresp
		.hps_0_h2f_BVALID                       (<connected-to-hps_0_h2f_BVALID>),                       //                                 .bvalid
		.hps_0_h2f_BREADY                       (<connected-to-hps_0_h2f_BREADY>),                       //                                 .bready
		.hps_0_h2f_ARID                         (<connected-to-hps_0_h2f_ARID>),                         //                                 .arid
		.hps_0_h2f_ARADDR                       (<connected-to-hps_0_h2f_ARADDR>),                       //                                 .araddr
		.hps_0_h2f_ARLEN                        (<connected-to-hps_0_h2f_ARLEN>),                        //                                 .arlen
		.hps_0_h2f_ARSIZE                       (<connected-to-hps_0_h2f_ARSIZE>),                       //                                 .arsize
		.hps_0_h2f_ARBURST                      (<connected-to-hps_0_h2f_ARBURST>),                      //                                 .arburst
		.hps_0_h2f_ARLOCK                       (<connected-to-hps_0_h2f_ARLOCK>),                       //                                 .arlock
		.hps_0_h2f_ARCACHE                      (<connected-to-hps_0_h2f_ARCACHE>),                      //                                 .arcache
		.hps_0_h2f_ARPROT                       (<connected-to-hps_0_h2f_ARPROT>),                       //                                 .arprot
		.hps_0_h2f_ARVALID                      (<connected-to-hps_0_h2f_ARVALID>),                      //                                 .arvalid
		.hps_0_h2f_ARREADY                      (<connected-to-hps_0_h2f_ARREADY>),                      //                                 .arready
		.hps_0_h2f_RID                          (<connected-to-hps_0_h2f_RID>),                          //                                 .rid
		.hps_0_h2f_RDATA                        (<connected-to-hps_0_h2f_RDATA>),                        //                                 .rdata
		.hps_0_h2f_RRESP                        (<connected-to-hps_0_h2f_RRESP>),                        //                                 .rresp
		.hps_0_h2f_RLAST                        (<connected-to-hps_0_h2f_RLAST>),                        //                                 .rlast
		.hps_0_h2f_RVALID                       (<connected-to-hps_0_h2f_RVALID>),                       //                                 .rvalid
		.hps_0_h2f_RREADY                       (<connected-to-hps_0_h2f_RREADY>),                       //                                 .rready
		.hps_0_h2f_rst_n                        (<connected-to-hps_0_h2f_rst_n>),                        //                  hps_0_h2f_reset.reset_n
		.hps_0_hps_io_emac1_inst_TX_CLK         (<connected-to-hps_0_hps_io_emac1_inst_TX_CLK>),         //                     hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_emac1_inst_TXD0           (<connected-to-hps_0_hps_io_emac1_inst_TXD0>),           //                                 .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_emac1_inst_TXD1           (<connected-to-hps_0_hps_io_emac1_inst_TXD1>),           //                                 .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_emac1_inst_TXD2           (<connected-to-hps_0_hps_io_emac1_inst_TXD2>),           //                                 .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_emac1_inst_TXD3           (<connected-to-hps_0_hps_io_emac1_inst_TXD3>),           //                                 .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_emac1_inst_RXD0           (<connected-to-hps_0_hps_io_emac1_inst_RXD0>),           //                                 .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_emac1_inst_MDIO           (<connected-to-hps_0_hps_io_emac1_inst_MDIO>),           //                                 .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_emac1_inst_MDC            (<connected-to-hps_0_hps_io_emac1_inst_MDC>),            //                                 .hps_io_emac1_inst_MDC
		.hps_0_hps_io_emac1_inst_RX_CTL         (<connected-to-hps_0_hps_io_emac1_inst_RX_CTL>),         //                                 .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_emac1_inst_TX_CTL         (<connected-to-hps_0_hps_io_emac1_inst_TX_CTL>),         //                                 .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_emac1_inst_RX_CLK         (<connected-to-hps_0_hps_io_emac1_inst_RX_CLK>),         //                                 .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_emac1_inst_RXD1           (<connected-to-hps_0_hps_io_emac1_inst_RXD1>),           //                                 .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_emac1_inst_RXD2           (<connected-to-hps_0_hps_io_emac1_inst_RXD2>),           //                                 .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_emac1_inst_RXD3           (<connected-to-hps_0_hps_io_emac1_inst_RXD3>),           //                                 .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_qspi_inst_IO0             (<connected-to-hps_0_hps_io_qspi_inst_IO0>),             //                                 .hps_io_qspi_inst_IO0
		.hps_0_hps_io_qspi_inst_IO1             (<connected-to-hps_0_hps_io_qspi_inst_IO1>),             //                                 .hps_io_qspi_inst_IO1
		.hps_0_hps_io_qspi_inst_IO2             (<connected-to-hps_0_hps_io_qspi_inst_IO2>),             //                                 .hps_io_qspi_inst_IO2
		.hps_0_hps_io_qspi_inst_IO3             (<connected-to-hps_0_hps_io_qspi_inst_IO3>),             //                                 .hps_io_qspi_inst_IO3
		.hps_0_hps_io_qspi_inst_SS0             (<connected-to-hps_0_hps_io_qspi_inst_SS0>),             //                                 .hps_io_qspi_inst_SS0
		.hps_0_hps_io_qspi_inst_CLK             (<connected-to-hps_0_hps_io_qspi_inst_CLK>),             //                                 .hps_io_qspi_inst_CLK
		.hps_0_hps_io_sdio_inst_CMD             (<connected-to-hps_0_hps_io_sdio_inst_CMD>),             //                                 .hps_io_sdio_inst_CMD
		.hps_0_hps_io_sdio_inst_D0              (<connected-to-hps_0_hps_io_sdio_inst_D0>),              //                                 .hps_io_sdio_inst_D0
		.hps_0_hps_io_sdio_inst_D1              (<connected-to-hps_0_hps_io_sdio_inst_D1>),              //                                 .hps_io_sdio_inst_D1
		.hps_0_hps_io_sdio_inst_CLK             (<connected-to-hps_0_hps_io_sdio_inst_CLK>),             //                                 .hps_io_sdio_inst_CLK
		.hps_0_hps_io_sdio_inst_D2              (<connected-to-hps_0_hps_io_sdio_inst_D2>),              //                                 .hps_io_sdio_inst_D2
		.hps_0_hps_io_sdio_inst_D3              (<connected-to-hps_0_hps_io_sdio_inst_D3>),              //                                 .hps_io_sdio_inst_D3
		.hps_0_hps_io_usb1_inst_D0              (<connected-to-hps_0_hps_io_usb1_inst_D0>),              //                                 .hps_io_usb1_inst_D0
		.hps_0_hps_io_usb1_inst_D1              (<connected-to-hps_0_hps_io_usb1_inst_D1>),              //                                 .hps_io_usb1_inst_D1
		.hps_0_hps_io_usb1_inst_D2              (<connected-to-hps_0_hps_io_usb1_inst_D2>),              //                                 .hps_io_usb1_inst_D2
		.hps_0_hps_io_usb1_inst_D3              (<connected-to-hps_0_hps_io_usb1_inst_D3>),              //                                 .hps_io_usb1_inst_D3
		.hps_0_hps_io_usb1_inst_D4              (<connected-to-hps_0_hps_io_usb1_inst_D4>),              //                                 .hps_io_usb1_inst_D4
		.hps_0_hps_io_usb1_inst_D5              (<connected-to-hps_0_hps_io_usb1_inst_D5>),              //                                 .hps_io_usb1_inst_D5
		.hps_0_hps_io_usb1_inst_D6              (<connected-to-hps_0_hps_io_usb1_inst_D6>),              //                                 .hps_io_usb1_inst_D6
		.hps_0_hps_io_usb1_inst_D7              (<connected-to-hps_0_hps_io_usb1_inst_D7>),              //                                 .hps_io_usb1_inst_D7
		.hps_0_hps_io_usb1_inst_CLK             (<connected-to-hps_0_hps_io_usb1_inst_CLK>),             //                                 .hps_io_usb1_inst_CLK
		.hps_0_hps_io_usb1_inst_STP             (<connected-to-hps_0_hps_io_usb1_inst_STP>),             //                                 .hps_io_usb1_inst_STP
		.hps_0_hps_io_usb1_inst_DIR             (<connected-to-hps_0_hps_io_usb1_inst_DIR>),             //                                 .hps_io_usb1_inst_DIR
		.hps_0_hps_io_usb1_inst_NXT             (<connected-to-hps_0_hps_io_usb1_inst_NXT>),             //                                 .hps_io_usb1_inst_NXT
		.hps_0_hps_io_spim0_inst_CLK            (<connected-to-hps_0_hps_io_spim0_inst_CLK>),            //                                 .hps_io_spim0_inst_CLK
		.hps_0_hps_io_spim0_inst_MOSI           (<connected-to-hps_0_hps_io_spim0_inst_MOSI>),           //                                 .hps_io_spim0_inst_MOSI
		.hps_0_hps_io_spim0_inst_MISO           (<connected-to-hps_0_hps_io_spim0_inst_MISO>),           //                                 .hps_io_spim0_inst_MISO
		.hps_0_hps_io_spim0_inst_SS0            (<connected-to-hps_0_hps_io_spim0_inst_SS0>),            //                                 .hps_io_spim0_inst_SS0
		.hps_0_hps_io_spim1_inst_CLK            (<connected-to-hps_0_hps_io_spim1_inst_CLK>),            //                                 .hps_io_spim1_inst_CLK
		.hps_0_hps_io_spim1_inst_MOSI           (<connected-to-hps_0_hps_io_spim1_inst_MOSI>),           //                                 .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_spim1_inst_MISO           (<connected-to-hps_0_hps_io_spim1_inst_MISO>),           //                                 .hps_io_spim1_inst_MISO
		.hps_0_hps_io_spim1_inst_SS0            (<connected-to-hps_0_hps_io_spim1_inst_SS0>),            //                                 .hps_io_spim1_inst_SS0
		.hps_0_hps_io_uart0_inst_RX             (<connected-to-hps_0_hps_io_uart0_inst_RX>),             //                                 .hps_io_uart0_inst_RX
		.hps_0_hps_io_uart0_inst_TX             (<connected-to-hps_0_hps_io_uart0_inst_TX>),             //                                 .hps_io_uart0_inst_TX
		.hps_0_hps_io_i2c0_inst_SDA             (<connected-to-hps_0_hps_io_i2c0_inst_SDA>),             //                                 .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_i2c0_inst_SCL             (<connected-to-hps_0_hps_io_i2c0_inst_SCL>),             //                                 .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_i2c1_inst_SDA             (<connected-to-hps_0_hps_io_i2c1_inst_SDA>),             //                                 .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_i2c1_inst_SCL             (<connected-to-hps_0_hps_io_i2c1_inst_SCL>),             //                                 .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_gpio_inst_GPIO09          (<connected-to-hps_0_hps_io_gpio_inst_GPIO09>),          //                                 .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_gpio_inst_GPIO35          (<connected-to-hps_0_hps_io_gpio_inst_GPIO35>),          //                                 .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_gpio_inst_GPIO37          (<connected-to-hps_0_hps_io_gpio_inst_GPIO37>),          //                                 .hps_io_gpio_inst_GPIO37
		.hps_0_hps_io_gpio_inst_GPIO40          (<connected-to-hps_0_hps_io_gpio_inst_GPIO40>),          //                                 .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_gpio_inst_GPIO41          (<connected-to-hps_0_hps_io_gpio_inst_GPIO41>),          //                                 .hps_io_gpio_inst_GPIO41
		.hps_0_hps_io_gpio_inst_GPIO44          (<connected-to-hps_0_hps_io_gpio_inst_GPIO44>),          //                                 .hps_io_gpio_inst_GPIO44
		.hps_0_hps_io_gpio_inst_GPIO48          (<connected-to-hps_0_hps_io_gpio_inst_GPIO48>),          //                                 .hps_io_gpio_inst_GPIO48
		.hps_0_hps_io_gpio_inst_GPIO53          (<connected-to-hps_0_hps_io_gpio_inst_GPIO53>),          //                                 .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_gpio_inst_GPIO54          (<connected-to-hps_0_hps_io_gpio_inst_GPIO54>),          //                                 .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_gpio_inst_GPIO61          (<connected-to-hps_0_hps_io_gpio_inst_GPIO61>),          //                                 .hps_io_gpio_inst_GPIO61
		.hps_0_mem_a                            (<connected-to-hps_0_mem_a>),                            //                     hps_0_memory.mem_a
		.hps_0_mem_ba                           (<connected-to-hps_0_mem_ba>),                           //                                 .mem_ba
		.hps_0_mem_ck                           (<connected-to-hps_0_mem_ck>),                           //                                 .mem_ck
		.hps_0_mem_ck_n                         (<connected-to-hps_0_mem_ck_n>),                         //                                 .mem_ck_n
		.hps_0_mem_cke                          (<connected-to-hps_0_mem_cke>),                          //                                 .mem_cke
		.hps_0_mem_cs_n                         (<connected-to-hps_0_mem_cs_n>),                         //                                 .mem_cs_n
		.hps_0_mem_ras_n                        (<connected-to-hps_0_mem_ras_n>),                        //                                 .mem_ras_n
		.hps_0_mem_cas_n                        (<connected-to-hps_0_mem_cas_n>),                        //                                 .mem_cas_n
		.hps_0_mem_we_n                         (<connected-to-hps_0_mem_we_n>),                         //                                 .mem_we_n
		.hps_0_mem_reset_n                      (<connected-to-hps_0_mem_reset_n>),                      //                                 .mem_reset_n
		.hps_0_mem_dq                           (<connected-to-hps_0_mem_dq>),                           //                                 .mem_dq
		.hps_0_mem_dqs                          (<connected-to-hps_0_mem_dqs>),                          //                                 .mem_dqs
		.hps_0_mem_dqs_n                        (<connected-to-hps_0_mem_dqs_n>),                        //                                 .mem_dqs_n
		.hps_0_mem_odt                          (<connected-to-hps_0_mem_odt>),                          //                                 .mem_odt
		.hps_0_mem_dm                           (<connected-to-hps_0_mem_dm>),                           //                                 .mem_dm
		.hps_0_oct_rzqin                        (<connected-to-hps_0_oct_rzqin>),                        //                                 .oct_rzqin
		.led_pio_export                         (<connected-to-led_pio_export>),                         //                          led_pio.export
		.rgm_reset_n                            (<connected-to-rgm_reset_n>)                             //                              rgm.reset_n
	);

